import base64, io
import numpy as np
from PIL import Image
from ....core.interfaces.base_detector import BaseDetector, DetectionResult


# Known watermark bit patterns from popular AI tools
# These are heuristic — not cryptographically verified
KNOWN_PATTERNS = {
    "stable_diffusion": [1, 0, 1, 1, 0, 1, 0, 0],
    "midjourney":       [0, 1, 0, 1, 1, 0, 1, 0],
}


class InvisibleWatermarkDetector(BaseDetector):
    """
    Detects invisible watermarks embedded by Stable Diffusion,
    Midjourney and similar tools using DWT-DCT steganographic analysis.
    """

    def __init__(self, model) -> None:
        super().__init__(model)
        self._decoder = None

    def _get_decoder(self):
        if self._decoder is None:
            from imwatermark import WatermarkDecoder
            self._decoder = WatermarkDecoder("bits", 48)
        return self._decoder

    def input_type(self) -> str:
        return "image"

    async def detect(self, payload: dict) -> DetectionResult:
        b64 = (payload.get("image_base64") or payload.get("content_b64") or "").split(",")[-1]
        if not b64:
            return DetectionResult(
                label="unknown", confidence=0.5,
                indicators=["No image data"])

        try:
            import cv2
            decoder = self._get_decoder()

            img_bytes = base64.b64decode(b64)
            img_pil   = Image.open(io.BytesIO(img_bytes)).convert("RGB")
            img_np    = np.array(img_pil)
            img_bgr   = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)

            # Decode watermark bits
            watermark_bits = decoder.decode(img_bgr, "dwtDct")

            if watermark_bits is None:
                return DetectionResult(
                    label="unknown",
                    confidence=0.4,
                    indicators=["No invisible watermark detected"],
                    metadata={"watermark_found": False},
                )

            has_watermark = any(watermark_bits)
            first_8       = list(watermark_bits[:8].astype(int))

            # Check against known patterns
            matched_tool = None
            for tool, pattern in KNOWN_PATTERNS.items():
                if first_8 == pattern:
                    matched_tool = tool
                    break

            if matched_tool:
                indicators = ["Invisible watermark detected in image"]
                indicators.append(f"Watermark pattern matches: {matched_tool}")
                indicators.append("Image likely generated by an AI image synthesis tool")
                return DetectionResult(
                    label="ai_generated",
                    confidence=0.88,
                    indicators=indicators,
                    metadata={
                        "watermark_found": True,
                        "matched_tool": matched_tool,
                        "bits_sample": first_8,
                    },
                )
            else:
                return DetectionResult(
                    label="unknown",
                    confidence=0.35,
                    indicators=["Invisible watermark analysis: no known pattern found"],
                    metadata={"watermark_found": False},
                )
        except ImportError:
            return DetectionResult(
                label="unknown", confidence=0.5,
                indicators=["invisible-watermark not installed — skipped"])
        except Exception as e:
            return DetectionResult(
                label="unknown", confidence=0.5,
                indicators=[f"Invisible watermark check failed: {str(e)[:100]}"])
