import { ThreatEvent, DashboardMetrics } from '@/types/threat';

export const INITIAL_THREATS: ThreatEvent[] = [
  {
    event_id: 'evt-c8b1a9f0-21a4-469b-8e12-9c12a77f001',
    created_at: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    category: 'deepfake',
    modality: 'audio',
    status: 'escalated',
    source: 'VoIP_Interception_Gateway_E1',
    label: 'Synthetic Voice Impersonation (CFO Voice Clone)',
    confidence: 0.96,
    risk_level: 'critical',
    indicators: [
      'Spectral discontinuity detected at 3.2kHz - 4.1kHz',
      'Phase vocoder vocoding artifacts in vocal tract formant transitions',
      'Zero ambient background noise room impulse response',
      'Caller ID spoofing header mismatch (P-Asserted-Identity mismatch)',
    ],
    score_factors: [
      'Target identity is Tier-1 Executive (CFO)',
      'High confidence (0.96) vocal synthesis acoustic model signature',
      'Urgent financial transfer instruction detected in transcription',
    ],
    explanation: 'Acoustic waveform analysis identifies neural voice cloning synthesis characteristic of ElevenLabs or VALL-E models. Audio lacks natural breathing pauses and displays phase artifacts across higher harmonics. The caller claimed to be Chief Financial Officer requiring emergency SWIFT transfer authorization.',
    recommended_actions: [
      'Immediately alert the Treasury & Accounts department of ongoing impersonation',
      'Reject pending SWIFT wire transfer #WT-940292',
      'Invoke out-of-band verification protocol via internal hardware token',
      'Block originating SIP gateway trunk IP (185.220.101.42)',
    ],
    mitre_mapping: ['T1656', 'T1566.002', 'T1078'],
    payload: {
      call_duration_seconds: 48,
      caller_id: '+1 (415) 555-0199',
      recipient_ext: '4021 (Treasury)',
      audio_sample_rate: '16000Hz',
      transcription: 'Hey Sarah, this is David. I am in an emergency airport transit and our supplier payment is overdue. Please immediately authorize the $185,000 transfer to Acme Global Escrow. I will sign off in Jira when I land.',
      f0_variance: 0.008,
      prosody_jitter_pct: 0.12,
    },
  },
  {
    event_id: 'evt-fa20d18e-57b1-4bc9-93e1-3d77ea4a002',
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    category: 'phishing',
    modality: 'email',
    status: 'complete',
    source: 'Mail_Filter_Inbound_Exchange',
    label: 'Microsoft 365 MFA Fatigue & Credential Harvester',
    confidence: 0.94,
    risk_level: 'critical',
    indicators: [
      'Lookalike domain: login-microsoftonline-sec-auth.com',
      'Reverse proxy Evilginx2 session cookie stealer detected',
      'SPF Fail: sender IP 194.26.29.112 not authorized for microsoft.com',
      'Urgency trigger words: "Account Termination in 2 Hours"',
    ],
    score_factors: [
      'Reverse proxy phishing capable of MFA bypass',
      'Targeted 14 IT department engineers',
      'Zero-day unregistered phishing host domain',
    ],
    explanation: 'Spearphishing email disguised as Microsoft Security Team alerting the recipient of expired authenticator tokens. Embedded hyperlinked button points to an Evilginx2 reverse-proxy server configured to capture active session tokens and bypass FIDO2/TOTP authentication.',
    recommended_actions: [
      'Purge message from all 14 recipient Exchange mailboxes via Microsoft Graph API',
      'Null-route domain login-microsoftonline-sec-auth.com at enterprise DNS resolver',
      'Revoke active OAuth tokens for any user who interacted with URL',
      'Trigger automated re-authentication challenge across Azure AD tenants',
    ],
    mitre_mapping: ['T1566.002', 'T1556', 'T1078.004'],
    payload: {
      sender: 'security-no-reply@microsoftonline-sec-auth.com',
      subject: 'URGENT: Microsoft 365 Authenticator Token Revocation Notice',
      recipients: ['eng-lead@cyberguard.internal', 'devops-team@cyberguard.internal'],
      links_extracted: ['https://login-microsoftonline-sec-auth.com/common/oauth2/v2.0/authorize'],
      attachment_names: [],
      tls_version: 'TLSv1.3',
    },
  },
  {
    event_id: 'evt-88a4c511-923f-4e09-ba22-1d54b81c003',
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
    category: 'log_anomaly',
    modality: 'auth_log',
    status: 'complete',
    source: 'SIEM_Collector_Prod_AWS',
    label: 'Distributed Password Spraying & Credential Stuffing',
    confidence: 0.89,
    risk_level: 'high',
    indicators: [
      '1,840 failed authentication attempts across 120 unique usernames',
      'Single uniform user-agent string used across 45 residential proxy IPs',
      'Rate throttled to 1 attempt per user every 180s to evade standard fail2ban',
      'Single successful authentication detected for account svc-backup-db',
    ],
    score_factors: [
      'Service account compromised (svc-backup-db)',
      'Coordinated botnet proxy egress pattern',
      'Targeted administrative service identities',
    ],
    explanation: 'Low-and-slow password spraying attack conducted from residential VPN nodes. The attacker systematically cycled through top 50 corporate passwords against active Active Directory accounts, resulting in a compromised service credential.',
    recommended_actions: [
      'Immediately rotate svc-backup-db credentials in AWS Secrets Manager',
      'Terminate active IAM session arn:aws:sts::109283741:assumed-role/backup-role',
      'Enforce IP whitelisting for svc-backup-db origin gateways',
      'Ingest residential proxy CIDRs into Web Application Firewall blocklist',
    ],
    mitre_mapping: ['T1110.003', 'T1078.004', 'T1071.001'],
    payload: {
      service: 'SSO / Okta LDAP Bridge',
      total_failed_attempts: 1840,
      targeted_users_count: 120,
      compromised_account: 'svc-backup-db',
      egress_ip_sample: ['185.191.171.12', '91.240.118.99', '45.154.255.81'],
      attack_duration_minutes: 42,
    },
  },
  {
    event_id: 'evt-23910cde-11bb-4592-a7f4-eef90184004',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    category: 'phishing',
    modality: 'qr',
    status: 'scored',
    source: 'Endpoint_EDR_MobileAgent',
    label: 'Quishing: Malicious QR Code in Corporate Parking Structure',
    confidence: 0.91,
    risk_level: 'high',
    indicators: [
      'Physical QR code sticker affixed over authentic parking sign',
      'Encoded URL redirect hops through 3 URL shorteners to evade crawler',
      'Final destination requests corporate payment card & employee ID',
    ],
    score_factors: [
      'Physical access vector targeting on-site employees',
      'Multi-hop evasive redirect infrastructure',
      'Phishing credential harvest targeting company credit cards',
    ],
    explanation: 'A fraudulent QR code sticker physically placed over campus visitor parking signs directed staff to a cloned payment portal designed to steal payment card credentials and badge IDs.',
    recommended_actions: [
      'Dispatch physical campus security to inspect all parking pay stations',
      'Send alert notification to mobile workforce in region North Campus',
      'Block final landing domain park-secure-pay-portal.xyz on mobile MDM devices',
    ],
    mitre_mapping: ['T1566.002', 'T1204'],
    payload: {
      qr_decoded_url: 'https://tinyurl.com/prk-fast-99 -> https://park-secure-pay-portal.xyz',
      device_os: 'iOS 17.5.1',
      reported_location: 'Campus West Garage, Level 2',
      extracted_meta: { host: 'park-secure-pay-portal.xyz', registrar: 'NameCheap' },
    },
  },
  {
    event_id: 'evt-6b3e944f-3c82-4aa8-9f1e-a4b88291005',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 88).toISOString(),
    category: 'api_abuse',
    modality: 'api_log',
    status: 'complete',
    source: 'API_Gateway_Kong_West',
    label: 'GraphQL Schema Probing & BOLA/IDOR Object Enumeration',
    confidence: 0.84,
    risk_level: 'medium',
    indicators: [
      'Systematic incrementing of customer_id parameter in POST /graphql',
      '500 requests/second from single TLS fingerprint JA3',
      'Responses included 403 Forbidden spikes followed by successful leak on customer #94018',
    ],
    score_factors: [
      'Rapid sequential object ID traversal (BOLA/IDOR)',
      'Evasion of per-IP rate limits using rotating IPv6 /64 blocks',
    ],
    explanation: 'Adversary leveraged a distributed IPv6 cluster to systematically query sequential customer records via an unsecured GraphQL resolver endpoint.',
    recommended_actions: [
      'Enable strict authorization checks on GraphQL Query.customer field',
      'Deploy global JA3 TLS fingerprint rate limiting rule in Cloudflare',
      'Investigate leaked customer record #94018 for sensitive data access',
    ],
    mitre_mapping: ['T1071.001', 'T1059.006'],
    payload: {
      endpoint: '/graphql',
      query_name: 'GetCustomerAccountDetails',
      rate_rps: 520,
      ip_count_ipv6: 840,
      total_probed_ids: 15400,
    },
  },
  {
    event_id: 'evt-0012bcfe-8891-45a1-901a-77bc33001006',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 179).toISOString(),
    category: 'phishing',
    modality: 'email',
    status: 'complete',
    source: 'Mail_Filter_Inbound_Exchange',
    label: 'Benign Corporate Newsletter: Engineering All-Hands Invite',
    confidence: 0.02,
    risk_level: 'safe',
    indicators: [
      'DKIM signature verified (d=cyberguard.internal)',
      'SPF pass (mfrom=news@cyberguard.internal, IP=10.0.4.15)',
      'DMARC pass policy=reject',
      'Zero suspicious hyperlinks or payload attachments',
    ],
    score_factors: [
      'Legitimate internal cryptographic mail headers',
      'Clean heuristic scanning across all NLP models',
    ],
    explanation: 'Legitimate internal corporate communication sent to all staff members regarding the quarterly all-hands conference.',
    recommended_actions: [
      'No remediation required; message successfully delivered to inbox',
    ],
    mitre_mapping: [],
    payload: {
      sender: 'all-hands@cyberguard.internal',
      subject: 'CyberGuard Q3 Engineering All-Hands & Roadmap Briefing',
      recipients: ['all-staff@cyberguard.internal'],
      links_extracted: ['https://wiki.cyberguard.internal/display/ENG/AllHandsQ3'],
      attachment_names: ['agenda.pdf'],
    },
  },
];

export const INITIAL_METRICS: DashboardMetrics = {
  total_events: 14820,
  critical_threats: 18,
  high_threats: 47,
  medium_threats: 132,
  safe_or_low: 14623,
  avg_confidence: 0.91,
  processing_rate: 340,
  active_agents: 4,
  category_distribution: {
    phishing: 6420,
    deepfake: 1180,
    log_anomaly: 5210,
    api_abuse: 2010,
    unknown: 0,
  },
  risk_distribution: {
    critical: 18,
    high: 47,
    medium: 132,
    low: 412,
    safe: 14211,
  },
};
